/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'thoma' at '03/10/16 10:52' with Gradle 3.1
 *
 * @author thoma, @date 03/10/16 10:52
 */


import me.rexim.morganey.gradle.Library
import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
