package me.rexim.morganey.gradle
/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'thoma' at '03/10/16 10:52' with Gradle 3.1
 *
 * @author thoma, @date 03/10/16 10:52
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
